新規投稿機能実装
tagkyauita/MAMP-Laravel-Post pull request #3
Opened 2021-10-22 08:58 UTC by tagkyauita

新規投稿機能を実装しました。
フォームリクエストも使ってみています。
ご確認のほどよろしくお願いいたします。

2021-10-22 10:52 UTC, hsg0830 requested changes
フォームリクエストも活用できて一歩前進ですね！
少しだけコメントしましたので、ご確認くださいね。

2021-10-22 10:52 UTC, hsg0830 commented on routes/web.php
> +Route::post('posts/{id}', 'PostsController@store')->name('posts.store');
実装内容を見るとログインユーザーのidを渡しているようですが、こちらはコントローラーでも取得できるので、わざわざパラメータとして渡す必要はなさそうです。
また、新規投稿の場合、postの視点からは`id`はまだ無いので、パラメータは不要ですね。

2021-10-22 10:52 UTC, hsg0830 commented on resources/views/posts/create.blade.php
> +                    <form class="upload" id="new_post" enctype="multipart/form-data" action="{{ route('posts.store', Auth::id()) }}" accept-charset="UTF-8" method="post">
ルーティングを検討した結果、必要であれば修正してくださいね。

2021-10-22 10:52 UTC, hsg0830 commented on app/Http/Controllers/PostsController.php
> +        $post->user_id = $id;
$idはパラメータとしてやり取りせずともここで取得できるかと思います。

2021-10-22 10:52 UTC, hsg0830 commented on app/Http/Controllers/PostsController.php
> +        $post->text = $request->input('body');
$request->title, $request->bodyのような書き方でも取得できるかと思います。

2021-10-22 10:52 UTC, hsg0830 commented on app/Http/Controllers/PostsController.php
> +        $validated = $request->validated();
フォームリクエストを使っているので、この行は不要では？

2021-10-23 06:40 UTC, tagkyauita commented on routes/web.php
> +Route::post('posts/{id}', 'PostsController@store')->name('posts.store');
コントローラーで取得できる
新規投稿ではidはまだない
覚えておきます！

2021-10-23 06:41 UTC, tagkyauita commented on resources/views/posts/create.blade.php
> +                    <form class="upload" id="new_post" enctype="multipart/form-data" action="{{ route('posts.store', Auth::id()) }}" accept-charset="UTF-8" method="post">
Auth::id()を削除しました

2021-10-23 06:43 UTC, tagkyauita commented on app/Http/Controllers/PostsController.php
> +        $post->text = $request->input('body');
変更しました！

2021-10-23 06:43 UTC, tagkyauita commented on app/Http/Controllers/PostsController.php
> +        $validated = $request->validated();
よく理解していませんでした💦
公式サイトに倣って書いてみたのですが関係ない項目だったんですね😅

2021-10-23 06:46 UTC, tagkyauita commented on app/Http/Controllers/PostsController.php
> +        $post->user_id = $id;
コントローラでAuth::id()として取得しました

2021-10-23 07:16 UTC, hsg0830 approved these changes
お疲れ様です！
マージしますね！
引き続き頑張ってくださいね！

2021-10-23 07:17 UTC, merged