Comment post
tagkyauita/MAMP-Laravel-Post pull request #7
Opened 2021-11-01 05:13 UTC by tagkyauita

コメント投稿機能を実装しました。

・実装箇所
CommentController.php
web.php

2021-11-03 01:58 UTC, hsg0830 requested changes
お疲れ様です。

遅くなりましたが、いくつかコメントしましたので、ご確認いただければと思います。

2021-11-03 01:58 UTC, hsg0830 commented on resources/views/posts/index.blade.php
> +                                    <input name="comment" value="" class="form-control comment-input border border-light mx-auto" placeholder="コメントを入力する">
- バリデーションで弾かれた際に、`old()`を用いて以前入力した内容が表示されるようにしてみてください。

- 上記を実現するには、76行目のcommmentのname属性は配列にする必要があるかと思います。

- `user_id`はコントローラーで取得しても良さそうですね。

2021-11-03 01:58 UTC, hsg0830 commented on app/Http/Requests/CommentPost.php
> +            'comment' => 'required|max:40'
- commmentのname属性は配列にした場合、バリデーションの書き方も工夫が必要ですね。

- `post_id`は、厳密には正の整数であり、postsテーブルのidカラムに存在するものでなければならないので、そのためのバリデーションが必要そうですね。postsテーブルのidカラムに存在するかどうかがチェックできると、自ずと正の整数しかないので、正の整数かどうかをチェックする記述は省略しても良さそうです。

- Bladeの箇所に書いたように、`user_id`はコントローラーで取得して良さそうですね。ログインしていないと入れないルーティングの中にさえあれば、ユーザーのIDは必ず取得できますので。

2021-11-03 01:58 UTC, hsg0830 commented on app/Http/Controllers/CommentsController.php
> +        $comment->user_id = $request->user_id;
- 一応、インスタンス生成時には、new Comment`()`のように、`()`を付けることが推奨されていたと思います。

- `user_id`の箇所は他で書いた通りです。

2021-11-03 03:26 UTC, tagkyauita commented on resources/views/posts/index.blade.php
> +                                    <input name="comment" value="" class="form-control comment-input border border-light mx-auto" placeholder="コメントを入力する">
・oldにて取得->全てのコメント欄にoldが入ってしまっています…
・name属性を配列にしてみましたが、配列にする理由がいまいち理解できていません。。
・user_idはコントローラで取得しました

2021-11-03 03:27 UTC, tagkyauita commented on app/Http/Requests/CommentPost.php
> +            'comment' => 'required|max:40'
・公式サイトで選別して、presentのバリデーションをかけてみましたが、自信無しです

2021-11-03 03:28 UTC, tagkyauita commented on app/Http/Controllers/CommentsController.php
> +        $comment->user_id = $request->user_id;
・()つけ忘れでした…付与しました！

2021-11-04 06:27 UTC, hsg0830 requested changes
お疲れ様です！
ほとんどできてますね！
少しだけコメント残したので、確認お願いします！

2021-11-04 06:27 UTC, hsg0830 commented on .vscode/settings.json
> +}
個人開発なので問題は無さそうですが、この類のものは、誰かと共有するなどの必要な理由がなければ、.gitignoreの対象にするのがいいかもですね。

2021-11-04 06:27 UTC, hsg0830 commented on app/Http/Controllers/CommentsController.php
> +        $comment->comment = $request->comments[$post_id];
`$pot_id`を追加で受け取らなくとも、`$request->post_id`で取得できそうですね。

2021-11-04 06:27 UTC, hsg0830 commented on resources/views/posts/index.blade.php
> +                                    <input name="comments[{{$post->id}}]" value="{{ old("comments.$post->id") }}" class="form-control comment-input border border-light mx-auto" placeholder="コメントを入力する
参考までに、valueの箇所は、
```{{ old('comments.' . $post->id) }}```
のようにも書けるかと思います。

2021-11-04 06:27 UTC, hsg0830 commented on resources/views/posts/index.blade.php
> +                            <form class="w-100" action="{{ route('comments.store', $post->id) }}" method="post">
今の実装の仕方ですと、先のコントローラーの箇所に書いたように、ルーティングでのpost_idの受け渡しは不要では？

2021-11-04 06:27 UTC, hsg0830 commented on routes/web.php
> +Route::post('comments/{id}', 'CommentsController@store')->name('comments.store');
パラメータの件、上に書いた通りです。

2021-11-04 06:30 UTC, tagkyauita commented on .vscode/settings.json
> +}
はっ…、不意にVSCodeの設定をいじっていたんですが、あれファイルに影響してたんですね…！せっかくなのでgitignoreしておきます。

2021-11-04 06:32 UTC, tagkyauita commented on app/Http/Controllers/CommentsController.php
> +        $comment->comment = $request->comments[$post_id];
頭混乱しててこんな単純なことにも気がつかなかったみたいです…本当ですね…素直にrequestから出してスマートにします。

2021-11-04 06:33 UTC, tagkyauita commented on resources/views/posts/index.blade.php
> +                                    <input name="comments[{{$post->id}}]" value="{{ old("comments.$post->id") }}" class="form-control comment-input border border-light mx-auto" placeholder="コメントを入力する
そんな書き方もあるんですね…、いまいちピンとこない書き方に思えますが…覚えておきます！

2021-11-04 06:34 UTC, tagkyauita commented on resources/views/posts/index.blade.php
> +                            <form class="w-100" action="{{ route('comments.store', $post->id) }}" method="post">
コントローラー修正するので、こちらも修正します。

2021-11-04 06:34 UTC, tagkyauita commented on routes/web.php
> +Route::post('comments/{id}', 'CommentsController@store')->name('comments.store');
こちらも同上にて修正かけます。

2021-11-04 06:51 UTC, hsg0830 requested changes
修正お願いします。

2021-11-04 06:51 UTC, hsg0830 commented on app/Http/Controllers/CommentsController.php
> +        $comment->comment = $request->post_id;
これだと、コメントの内容取り出せてないですね。。。

2021-11-04 06:51 UTC, hsg0830 commented on .vscode/settings.json
> +}
このファイル、上がったままになってますね、、

2021-11-04 07:20 UTC, tagkyauita commented on app/Http/Controllers/CommentsController.php
> +        $comment->comment = $request->post_id;
検証用のブラウザリフレッシュせずに動作検証してました…
正しく動くコードに修正しました💦

2021-11-04 07:21 UTC, tagkyauita commented on .vscode/settings.json
> +}
.gitignoreの使い方の調べが適当過ぎました、すみません。
今度は外れてると思うのですが…

2021-11-04 10:22 UTC, hsg0830 approved these changes
マージしますね！

2021-11-04 10:22 UTC, merged